package riot

const (
	RegionBrasil            = "br1"
	RegionEuropeNorthEast   = "eun1"
	RegionEuropeWest        = "euw1"
	RegionJapan             = "jp1"
	RegionKorea             = "kr"
	RegionLatinAmericaNorth = "la1"
	RegionLatinAmericaSouth = "la2"
	RegionNorthAmerica      = "na1"
	RegionOceania           = "oc1"
	RegionPBE               = "pbe1"
	RegionPhilippines       = "ph2"
	RegionRussia            = "ru"
	RegionSingapore         = "sg2"
	RegionThailand          = "th2"
	RegionTurkey            = "tr1"
	RegionTaiwan            = "tw2"
	RegionVietnam           = "vn2"

	RankedSolo5x5Queue = "RANKED_SOLO_5x5"
	RankedFlexSRQueue  = "RANKED_FLEX_SR"
	RankedFlexTTQueue  = "RANKED_FLEX_TT"

	IronTier        = "IRON"
	BronzeTier      = "BRONZE"
	SilverTier      = "SILVER"
	GoldTier        = "GOLD"
	PlatinumTier    = "PLATINUM"
	EmeraldTier     = "EMERALD"
	DiamondTier     = "DIAMOND"
	MasterTier      = "MASTER"
	GrandMasterTier = "GRANDMASTER"
	ChallengerTier  = "CHALLENGER"

	DivisionOne   = "I"
	DivisionTwo   = "II"
	DivisionThree = "III"
	DivisionFour  = "IV"
)
